spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/weather?serverTimezone=UTC&characterEncoding=UTF-8
    username: weather_user
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true